source 'https://git.coding.net/wubianxiaoxian/SKFFMPrivateLib.git'
source 'https://github.com/CocoaPods/Specs.git'  #官方仓库的地址

use_frameworks!

target 'SKFDownLoadListern_Example' do
  pod 'SKFDownLoadListern', :path => '../'

  target 'SKFDownLoadListern_Tests' do
    inherit! :search_paths

    
  end
end
